server:
  port: 8011

spring:
  application:
    name: eureka-producer

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka/